# Array Operations

NumPy is not just good at storing large amounts of data, it's also very efficient at performing calculations and makes carrying out these calculations very convenient. This notebook discusses some of these calculations and the syntax used to invoke them.

## Arithmetic and Comparison Operations

Simple arithmetic and comparison operators can be performed using NumPy arrays. When such an operation is placed between two NumPy arrays, the operation is performed "element-wise". This means that the operation is performed on each element of the arrays to create the corresponding element of the new array. For instance:

In [2]:
import numpy as np

a = np.array([2,4,6])
b = np.array([1,4,7])

print("Addition: ", a + b)
print("Subtraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Exponentiation: ", a ** b)
print("Integer Division: ", a // b)
print("Modulo: ", a % b)
print("Negative: ", -a)

# This is also works with comparison operators
print("Greater Than: ", a > b)
print("Less Than: ", a < b)
print("Greater Than or Equal: ", a >= b)
print("Less Than or Equal: ", a <= b)
print("Equal: ", a == b)
print("Not Equal: ", a != b)
print("XOR: ", a ^ b)

Addition:  [ 3  8 13]
Subtraction:  [ 1  0 -1]
Multiplication:  [ 2 16 42]
Division:  [2.         1.         0.85714286]
Exponentiation:  [     2    256 279936]
Integer Division:  [2 1 0]
Modulo:  [0 0 6]
Negative:  [-2 -4 -6]
Greater Than:  [ True False False]
Less Than:  [False False  True]
Greater Than or Equal:  [ True  True False]
Less Than or Equal:  [False  True  True]
Equal:  [False  True False]
Not Equal:  [ True False  True]
XOR:  [3 0 1]


## Applying the Same Operation to Every Element

It's possible to apply the same operation to every element of an array using an operator and a scalar value. The array and the integer may be in either order.

In [3]:
import numpy as np

a = np.arange(1, 4)
print("a: ", a)
print("Addition: ", 2 + a)
print("Left Subtraction: ", 2 - a)
print("Right Subtraction: ", a - 2)
print("Multiplication: ", a * 2)
print("Left Division: ", a / 2)
print("Right Division: ", 2 / a)
print("Left Exponentiation: ", 2 ** a)
print("Right Exponentiation: ", a ** 2)
print("Left Integer Division: ", 2 // a)
print("Right Integer Division: ", a // 2)
print("Left Modulo: ", 2 % a)
print("Right Modulo: ", a % 2)

a:  [1 2 3]
Addition:  [3 4 5]
Left Subtraction:  [ 1  0 -1]
Right Subtraction:  [-1  0  1]
Multiplication:  [2 4 6]
Left Division:  [0.5 1.  1.5]
Right Division:  [2.         1.         0.66666667]
Left Exponentiation:  [2 4 8]
Right Exponentiation:  [1 4 9]
Left Integer Division:  [2 1 0]
Right Integer Division:  [0 1 1]
Left Modulo:  [0 0 2]
Right Modulo:  [1 0 1]


## Exercise

Look at the code in the cell below, but don't run it yet. Instead, write down what you think will be printed in each case. Then, run the code and check you get the results you expect.

In [5]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

print("Case 1: ", a + b) # [4 6]
print("Case 2: ", a / 2) # [0.5 1.]
print("Case 3: ", a ** b) # [1 16]
print("Case 4: ", 2 - a) # [1 0]
print("Case 5: ", a - b * 2) # [-5 -6] # Remember the order of operations

Case 1:  [4 6]
Case 2:  [0.5 1. ]
Case 3:  [ 1 16]
Case 4:  [1 0]
Case 5:  [-5 -6]


## Statistics of Arrays

NumPy has a number of built-in functions for performing statistical calculations on arrays. These include:

In [7]:
a = np.array([1, 4, 3, 5, 2])

print("a: ", a)
print("Sum: ", a.sum())
print("Minimum: ", a.min())
print("Maximum: ", a.max())
print("Mean: ", a.mean())
print("Median: ", np.median(a))
print("Standard Deviation: ", a.std())
print("Variance: ", a.var())
print("Range:", np.ptp(a))
# print("Range:", a.ptp())    RETIRED

a:  [1 4 3 5 2]
Sum:  15
Minimum:  1
Maximum:  5
Mean:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Variance:  2.0
Range: 4


AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.

We can also perform useful operations on an array of bools (such as those generated by a comparison operator):

In [9]:
a = np.array([True, True, False, True])

print("a: ", a)
print("All: ", a.all()) # Will be True if all elements are True
print("Any: ", a.any()) # Will be True if any elements are True
print("Number of Trues: ", a.sum()) # For the purposes of a sum, True is 1 and False is 0
print(a[0]*50)

# We can combine these functions with operators
# For example, to check if all elements are less than 10:
b = np.array(np.array([1, 2, 3, 4]))
print("All less than 10: ", (b < 10).all())


a:  [ True  True False  True]
All:  False
Any:  True
Number of Trues:  3
50
All less than 10:  True


## More Complex Functions

Many complex mathematical functions which operate on scalars in Python are available from the ```math``` module, such as the ```sin``` function. These functions will work on NumPy arrays with a size of 1 (and return a scalar), but will not work on larger arrays:

In [10]:
import numpy as np
import math

print(math.sin(2))
print(math.sin(np.array([1])))
print(math.sin(np.arange(3)))

0.9092974268256817
0.8414709848078965


/tmp/ipykernel_41434/280747599.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(math.sin(np.array([1])))


TypeError: only length-1 arrays can be converted to Python scalars

Fortunately, many of these functions are replicated within the NumPy array and will operate element-wise on an array passed to it:

In [11]:
import numpy as np

# Here we multiply the array [1 2 3] by a quarter
a = np.arange(1,4) * 0.25
print("a: ", a)
print("sin: ", np.sin(a))
print("arccos: ", np.arccos(a)) # Note that names are not always the same as in the math module
print("log: ", np.log(a))
print("log2: ", np.log2(a))
print("log10: ", np.log10(a))
print("sqrt: ", np.sqrt(a))
print("sum: ", np.sum(a))

a:  [0.25 0.5  0.75]
sin:  [0.24740396 0.47942554 0.68163876]
arccos:  [1.31811607 1.04719755 0.72273425]
log:  [-1.38629436 -0.69314718 -0.28768207]
log2:  [-2.        -1.        -0.4150375]
log10:  [-0.60205999 -0.30103    -0.12493874]
sqrt:  [0.5        0.70710678 0.8660254 ]
sum:  1.5


## Vector and Matrix Operations

NumPy is designed to hold vectors, matrices, tensors and so on. It also contains functions to perform common operations relevant to these data types. For instance:

In [12]:
import numpy as np

matrix = np.arange(4).reshape([2,2])
vector1 = np.array([1,2])
vector2 = np.array([3,4])

print("Matrix: ", matrix)
print("Vector1: ", vector1)
print("Vector2: ", vector2)

print("Dot product", np.dot(vector1, vector2))
print("Matrix-vector multiplication: ", np.matmul(matrix, vector1))
print("Matrix-matrix multiplication: ", np.matmul(matrix, matrix))
print("Matrix power: ", np.linalg.matrix_power(matrix, 3))
print("Determinant: ", np.linalg.det(matrix))
print("Transpose: ", np.transpose(matrix))
print("Inverse: ", np.linalg.inv(matrix))
print("Eigenvectors and eigenvalues: ", np.linalg.eig(matrix))

Matrix:  [[0 1]
 [2 3]]
Vector1:  [1 2]
Vector2:  [3 4]
Dot product 11
Matrix-vector multiplication:  [2 8]
Matrix-matrix multiplication:  [[ 2  3]
 [ 6 11]]
Matrix power:  [[ 6 11]
 [22 39]]
Determinant:  -2.0
Transpose:  [[0 2]
 [1 3]]
Inverse:  [[-1.5  0.5]
 [ 1.   0. ]]
Eigenvectors and eigenvalues:  EigResult(eigenvalues=array([-0.56155281,  3.56155281]), eigenvectors=array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]]))


## Exercise: Cartesian Coordinates

A location in 3d Cartesian space may be represented by (x,y,z) coordinates. This may be represented by a
dimension 1 array with size 3.

In the cell below:
* Create a 1d array with three elements to represent Position A, which is at (1,2,1)
* Calculate the location of Position B, which has a displacement of (3,-4,1) from Position A
* Calculate the location of Position C, which is twice as far from the origin as Position B
* Calculate the location of position D, which is found by rotating position C 45 $^{o}$ around the z axis (clockwise
when viewed from above). To rotate a location around the z axis in this manner by an angle $\theta$ , it may be
multiplied by the matrix:
$
\begin{pmatrix}
\cos(\theta) & -\sin(\theta) & 0 \\ 
\sin(\theta) & \cos(\theta) & 0 \\ 
0 & 0 & 1
\end{pmatrix}
$
* Calculate the straight line distance between Position D and the origin

In [29]:
import math
import numpy as np

A=np.array([1,2,1])
print(A)
print(np.linalg.norm(A))
print("----")

B=A+np.array([3,-4,1])
print(B)
print(np.linalg.norm(B))
print("----")

C=B*2
print(C)
print(np.linalg.norm(C))
print("----")

r_deg=45
r_rad=r_deg/(2*math.pi)
r_sin=math.sin(r_rad)
r_cos=math.cos(r_rad)
r_matrix=np.zeros([3,3])
r_matrix[2,2]=1
r_matrix[:2,:2]=np.array([r_cos,-r_sin,r_sin,r_cos]).reshape(2,2)
print(r_matrix)
D=np.matmul(r_matrix,C)
print(D)
print(np.linalg.norm(D))
print("----")


[1 2 1]
2.449489742783178
----
[ 4 -2  2]
4.898979485566356
----
[ 8 -4  4]
9.797958971132712
----
[[ 0.63808548 -0.76996553  0.        ]
 [ 0.76996553  0.63808548  0.        ]
 [ 0.          0.          1.        ]]
[8.18454597 3.60738234 4.        ]
9.797958971132713
----


A sample solution can be found in [```Sample Solutions/Sample Solutions 3 - Array Operations.ipynb```](Sample%20Solutions/Sample%20Solutions%203%20-%20Array%20Operations.ipynb).