# Connect Four Exercise

Here's an open-ended exercise using 2D numpy arrays. The idea is to get a bit more practice with writing functions and loops, and thinking about array indexing. 

Nothing will be marked, it's just for fun. 
Work alone or in small groups.
Do as much as you like.


For each of the exercises in this notebook, sample solutions can be found in [```Sample Solutions/Sample Solutions 8 - Connect Four.ipynb```](Sample%20Solutions/Sample%20Solutions%208%20-%20Connect%20Four.ipynb).

### The scenario

<center><img src="../Resources/Connect4.jpg" style="height:300px" /></center>

The game [Connect Four](https://en.wikipedia.org/wiki/Connect_Four) is played on a vertical grid with 7 columns and 6 rows.

We can represent the state of the game using an integer matrix, where 1 is a red counter, 2 is a yellow counter and 0 is an empty cell.

The most natural coordinate system for the game is **(column,row)**, counting columns from left to right and rows from bottom to top. (We'll assume that both players are sitting on the same side of the board.)

At the start of the game, the board looks like this:


In [3]:
import numpy as np

board_0 = np.zeros((7,6),int)  # specifies int data type
print(board_0)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


(Notice that when the array is printed like this, the board is shown rotated by 90 degrees clockwise).

Red goes first, placing a counter in the fifth column:

In [4]:
board_1 = board_0.copy()
board_1[4,0] = 1
print(board_1)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


After seven moves, the board looks like this:

In [5]:
board_7 = np.array([[0, 0, 0, 0, 0, 0],
                    [1, 0, 0, 0, 0, 0],
                    [2, 1, 1, 0, 0, 0],
                    [1, 2, 0, 0, 0, 0],
                    [2, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0]])
print(board_7)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 1 1 0 0 0]
 [1 2 0 0 0 0]
 [2 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Task 1

It's already annoying having to strain my neck to look at these boards. I'm trying to write a function that prints a representation of the board in the correct orientation.

I managed to print it without all of those square brackets, but the orientation is still wrong. Please can you fix it for me?


In [6]:
def display(board):
    yellow="\U0001F7E1"
    red="\U0001F534"
    blank = "\u2022\u2009"
    # blank = "\u25A3"
    print_chr=[blank, red, yellow]
    for i in range(6):
        for j in range(7):
            print(print_chr[board[j,5-i]], end=" ")
        print()     
    print()
display(board_7)
            

•  •  •  •  •  •  •  
•  •  •  •  •  •  •  
•  •  •  •  •  •  •  
•  •  🔴 •  •  •  •  
•  •  🔴 🟡 •  •  •  
•  🔴 🟡 🔴 🟡 •  •  



### Task 2

We could make it easier for a player to make a move.

Complete the function `do_move(board, player, column)`, which returns the new state of the board after a move is made in the column specified:

In [7]:
def do_move(board, player, column):
    """Returns the new board configuration after the specified move.

    Parameters:
        board (numpy.ndarray): The current board configuration.
        player (int): The player who is moving (1 or 2).
        column (int): The column in which they play (0-6).

    Returns:
        numpy.ndarray: The board configuration after the move. """
    
    new_board = board.copy()
    
    # do some things here...

    for i in range(7): # deliberately 1 more than allowed to throw an error if column is full
        try:
            if new_board[column,i]==0:
                new_board[column,i]=player
                break
        except:
            print("Illegal move!")

    return new_board
    
board_8 = do_move(board_7, 1, 2)
display(board_8)

•  •  •  •  •  •  •  
•  •  •  •  •  •  •  
•  •  🔴 •  •  •  •  
•  •  🔴 •  •  •  •  
•  •  🔴 🟡 •  •  •  
•  🔴 🟡 🔴 🟡 •  •  



### Task 3

Write a function `get_move(board, player)` that returns a legal move (column index) for the given player.

In [10]:
def in_range(x, max):
    return x >= 0 and x < max

def eval_line(board, player, column, row, column_dir, row_dir):
    
    eval_score = 0
    check_column = column + column_dir
    check_row = row + row_dir
    match_score = 2
    while in_range(check_column,7) and in_range(check_row,6) and (board[check_column,check_row]==player or board[check_column,check_row]==0):
        if board[check_column,check_row]==0:
            eval_score += match_score / 2
            break
        else:
            eval_score += match_score
            match_score += 1
            check_column += column_dir
            check_row += row_dir
    return eval_score

def eval_board(board, player, column, row):
    eval_score = 1
    for i in range(-1,2):
        for j in range(-1,2):
            if i==0 and j==0:
                continue
            eval_score += eval_line(board, player, column, row, i, j)
    print(f"score: {eval_score}")
    return eval_score

def get_move(board, player):
    best_col = -1
    best_eval = -1
    for column in range(7):
        temp_board=board.copy()
        for row in range(6):
                if board[column, row] == 0:
                    print(f"column: {column}")
                    temp_board[column,row] = player
                    temp_eval = eval_board(temp_board, player, column, row)
                    if temp_eval > best_eval:
                        print("found better")
                        best_eval = temp_eval
                        best_col = column
                    break
    if best_col == -1:
        print("Board is full!")
        return None
    
    return best_col
            
column = get_move(board_8, 1)
board_9 = do_move(board_8, 1, column)
display(board_9)

column: 0
score: 3.0
found better
column: 1
score: 7.0
found better
column: 2
score: 8.0
found better
column: 3
score: 7.0
column: 4
score: 10.0
found better
column: 5
score: 7.0
column: 6
score: 4.0
•  •  •  •  •  •  •  
•  •  •  •  •  •  •  
•  •  🔴 •  •  •  •  
•  •  🔴 •  •  •  •  
•  •  🔴 🟡 🟡 •  •  
•  🔴 🟡 🔴 🟡 •  •  



### Task 4 (harder)

Write a function `winner(board)` that returns an integer:

* -1 if the game is not yet over.
* 0 if the game is a draw.
* 1 if red has won.
* 2 if yellow has won.



### Task 5

You have *almost* made a Connect Four simulation. 
Can you finish it so that I can play against the computer? 


In [9]:
# Might be useful...
response = input("Please enter a column number:")
col = int(response)
print(col)

ValueError: invalid literal for int() with base 10: ''

### Task 6

Can you improve your `get_move` function to make a more strategic move?